### ISSUE TITLE
Split analyses into components in Shiny app

### ISSUE THREAD

**Issue by schuemie** [ohdsi-studies/ScyllaEstimation#1]
There are currently many analyses (analysis IDs), and these even interact with the choice of target and comparator, making it very hard for users to navigate the Shiny app. We should parse the target, comparator, and analyses like we did [here](http://shiny.ohdsi.org:2020/AhasHfBkleAmputation/), so the user can for example select ACEs vs ARBs, then select the model (Cox or logistic), then other options like washout period.

(Not sure if the code can be re-used, but the example cited above is implemented [here](https://github.com/OHDSI/StudyProtocols/blob/master/AhasHfBkleAmputation/R/PrepareResultsForAnalysis.R#L30))

**Comment by msuchard** [comment]
Can I give this a try?

**Comment by schuemie** [comment]
Yes please. Do you want me to share the results files (exported CSV files) with you?

**Comment by msuchard** [comment]
A first working draft is here 85e590a67a1553367a4953d799c0649129033c34

**Comment by schuemie** [comment]
[Now](https://github.com/ohdsi-studies/ScyllaEstimation/commit/5fa44418525560f8a609e083f493b8475a1d9bc8) working in develop branch
