### ISSUE TITLE
SynthesizePositiveControls argument in 'execute' function

### ISSUE THREAD

**Issue by tfalcs** [ohdsi-studies/ScyllaEstimation#7]
@schuemie , @anthonysena 

There seems to be an inconsistency with the set of arguments in the 'execute' function of the 'CodeToRun.R' file and in the construction of the function in the 'Main.R' file. The latter doesn't have the 'SynthesizePositiveControls' argument, whereas the former does. When I comment out the 'SynthesizePositiveControls' argument in the 'execute' function in the CodeToRun script, it runs just fine. Otherwise, I get the following: 

> execute(connectionDetails = connectionDetails,
+         cdmDatabaseSchema = cdmDatabaseSchema,
+         cohortDatabaseSchema = cohortDatabaseSchema,
+         cohortTable = cohortTable,
+         oracleTempSchema = oracleTempSchema,
+         outputFolder = outputFolder,
+         databaseId = databaseId,
+         databaseName = databaseName,
+         databaseDescription = databaseDescription,
+         createCohorts = TRUE,
+         synthesizePositiveControls = TRUE,
+         runAnalyses = TRUE,
+         packageResults = TRUE,
+         maxCores = maxCores)
Error in execute(connectionDetails = connectionDetails, cdmDatabaseSchema = cdmDatabaseSchema,  : 
  unused argument (synthesizePositiveControls = TRUE)
No suitable frames for recover()

**Comment by schuemie** [comment]
Thanks Thomas, and sorry I missed that. We're not using positive control synthesis in this study, so I decided to remove it from the code altogether.
